### ISSUE TITLE
GridView, can you help to provide freeze pane function?

### ISSUE THREAD

**Issue by ScottHuangZL** [yiisoft/yii-dataview#12]
Dear Yii2 Team,

Some grid widget can provide freeze top header function. However, I do not find any Yii2 grid can help to freeze left columns function.

Do you have a plan to enable GridView to provide function to freeze first several columns when scroll to right, just like excel freeze pane? thanks.

Regards,
Scott Huang

**Comment by glpzzz** [comment]
This relies on some combination of CSS and JS, perhaps defining a fixed height for the table, etc. I think this current of GridView (with no gridview.js) is more about a native HTML table. This one could benefit from improvements provided by other plugins like DataTables.

With this in mind, should GridView include these features? Any, following a CSS only proposal, which looks mostly good when background is set for the cells (used Bootstrap to aid on general styling) https://codepen.io/glpzzz/pen/GRbLaGo

If this is accepted as expected result for "fixed header" I can create the PR to add the required options to the GridView widget.

**Comment by vjik** [comment]
> I can create the PR to add the required options to the GridView widget.

Seems, this feature require to add CSS classes only, isn't it?
What options are needed?

**Comment by glpzzz** [comment]
> What options are needed?

`fixedHeader` as a boolean. If `true`, it adds the required CSS. I also need to add something like `heightWhenFixedHeader`, but I don't like having 2 attributes for the same thing.

I also don't like making `fixedHeader` accept the height instead of the boolean. It's not "semantic".

But yes, the idea is to add some attribute to `GridView` that flags the addition of the CSS shown in the codepen.

**Comment by vjik** [comment]
We can fix:
- header,
- footer,
- top N rows,
- bottom N rows,
- left N columns,
- right N columns. 

So, we need methods that enable/disable fixing and methods that configure fixing (set of CSS classes and/or CSS styles). Right?

In app we can globally configure grid view (set of CSS classes) and in concrete grid view set what should be fixed.

**Comment by glpzzz** [comment]
I'm still not sure if those options should be implemented in this `GridView` when there are other options already with those features. I don't think that the CSS only solution is completely good. 

This is my reference, at least for fixed headers:
- https://datatables.net/examples/basic_init/scroll_y.html
- https://datatables.net/examples/basic_init/scroll_xy.html

Are we trying to achieve something like that?

**Comment by samdark** [comment]
No. Something like this: https://codepen.io/chriscoyier/pen/PrJdxb

**Comment by vjik** [comment]
This package provide HTML code only. CSS/JS should be added by user or other package.

**Comment by samdark** [comment]
Then closing this one.

**Comment by vjik** [comment]
It can be implemented as set of methods:

1) Methods that set freeze columns/rows/header/footer. For example `freezeHeader()` or `freezeTopRows(2)`.

2) Methods that set freeze classes. For example, `freezeConfiguration(FreezeConfiguration $configuration);` where `FreezeConfiguration` is PHP class with HTML classses for header/footer/row/column/table when freeze is enabled.

**Comment by glpzzz** [comment]
Considering that the core of the solution is provided via CSS, I think the current implementation is doing enough by allowing to set ID and/or classes for the widget.

That way, it's easy to define the freezing style for the `#gridview1` or all the grid views with a certain class.
